name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.9.13, 3.10.8, 3.11.0]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build for development
      run: |
        python3 -m venv venv
        . venv/bin/activate
        cargo build
        maturin develop
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --sdist -o dist --find-interpreter
    - name: Use the python module
      run: |
        . venv/bin/activate
        python3 -c "import rorm_python; import rorm_python.bindings; print('OK');"
        python3 -m rorm_python --help
