name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: messense/maturin-action@v1
      with:
        command: develop
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --sdist -o dist --find-interpreter
    - name: Use the python module
      run: |
        python3 -m rorm_python --help
